language: php
php:
#  - 5.4
  - 5.5
#  - hhvm

#matrix:
#  allow_failures:
#    - php: hhvm
  
before_install:
  - composer self-update
#  - composer create-project --dev --no-interaction --no-progress typo3/neos-base-distribution neos_root 1.1.0-beta2
#  - git clone git://git.typo3.org/Neos/Distributions/Base.git neos_root
  - ls -al

  - composer install --prefer-source
  - ls -al
  - ls -al Build/
