language: php
php:
#  - 5.4
  - 5.5
#  - hhvm

#matrix:
#  allow_failures:
#    - php: hhvm
  
before_install:
#  - git clone git://git.typo3.org/Neos/Distributions/Base.git neos_root
#  - cd neos_root
#  - git checkout 1.1

#  - composer self-update
#  - composer install --prefer-source

  # Enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - cat ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  #- echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # Configure Nginx
  - sudo apt-get install nginx && nginx -v
  - sudo cp -fR Build/Nginx/* /etc/nginx/.
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/nginx/sites-enabled/neos.conf
  - cat /etc/nginx/sites-enabled/neos.conf
  - echo "127.0.0.1 neos neos.dev neos.test" | sudo tee -a /etc/hosts
  - sudo service nginx restart
