language: php
php:
#  - 5.4
  - 5.5
#  - hhvm

#matrix:
#  allow_failures:
#    - php: hhvm
  
before_install:
  - git clone git://git.typo3.org/Neos/Distributions/Base.git neos_root
  - cd neos_root
  - git checkout 1.1

  - composer self-update
  - composer install --prefer-source

  - ls -al
  - php -i
  - ls -al ~/.phpenv/versions/$(phpenv version-name)/etc
  - ls -al ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d
