language: php
php:
#  - 5.4
  - 5.5
#  - hhvm

#matrix:
#  allow_failures:
#    - php: hhvm
  
before_install:
#  - git clone git://git.typo3.org/Neos/Distributions/Base.git neos_root
#  - cd neos_root
#  - git checkout 1.1

#  - composer self-update
#  - composer install --prefer-source

  - sudo apt-get install nginx
  - nginx -v

  - ls -al
  - php -i
  - ls -al ~/.phpenv/versions/$(phpenv version-name)/etc
  - ls -al ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d
  - cat ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default
  - ls -al /etc/nginx/
  - ls -al /etc/nginx/sites-enabled
  - cat /etc/nginx/nginx.conf
